Assignment
Import numpy as np

In [ ]:
import numpy as np

Make a python list => [1,2,3,4,5]

Convert it into numpy array and print it

In [ ]:
lists=[1,2,3,4,5]
lists2=np.array(lists)
print(lists2)

[1 2 3 4 5]


Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]]

Convert it into numpy array and print it

In [ ]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat2=np.array(mat)
print(mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

[ [1,3,5],

[7,9,11],

[13,15,17] ]

In [ ]:
arr=np.arange(1,18,2).reshape(3,3)
print(arr)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [ ]:
arr2=np.array(np.random.rand(10)*10)
print(arr2)

[9.21322637 9.80938405 1.85697558 1.98333296 1.18344102 9.56819252
 5.2811133  5.20055839 6.52692004 9.12361983]


Create numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

In [ ]:
arr3=np.array([1,2,3,4,5]).reshape(5,1)
print(arr3)

[[1]
 [2]
 [3]
 [4]
 [5]]


Print the shape of the above created array

In [ ]:
arr3.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [ ]:
arr4=np.array(np.arange(1,11))
print(arr4[2],arr4[3],arr4[8])

3 4 9



Print alternate elements of that array

In [ ]:
print(arr4[::2])

[1 3 5 7 9]


Change last 3 elements into 100 using broadcasting and print

In [ ]:
arr4[-3:]=100
print(arr4)

[  1   2   3   4   5   6   7 100 100 100]


Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [ ]:
arr6=np.array(np.arange(1,26).reshape(5,5))
print(arr6[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
